name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'

    - name: Change Directory to Parent
      run: cd /home/runner/work/balestech_suite/balestech_suite/modules

    - name: Local Directory to Parent
      run: pwd
      
    - name: Build with Maven
      run: mvn clean install -B -DskipTests=false

    - name: Run Tests
      run: mvn test
