server:
  port: 8200
  servlet:
    context-path: /kafka


#KAFKA - MESSAGES
spring:
  kafka:
    bootstrap-servers: kafka:9092


#ACTUATOR - MONITORING
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always