server:
  port: 8051
  servlet:
    context-path: /b3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/balestech
    username: balestech
    password: balestech
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092